### ISSUE TITLE
Allow developers to access the Order resource

### ISSUE THREAD

**Issue by kimberly-bird** [blathering-barnacles/Bangazon-3#4]
Verbs to be supported

1. GET
1. POST
1. PUT
1. DELETE

* User should be able to GET a list, and GET a single item.
* When an order is deleted, every line item _(i.e. entry in OrderProduct)_ should be removed
* Should be able to filter out completed orders with the `?completed=false` query string parameter. If the parameter value is `true`, then only completed order should be returned.
* If the query string parameter of `?_include=products` is in the URL, then the list of products in the order should be returned.
* If the query string parameter of `?_include=customers` is in the URL, then the customer representation should be included in the response.

**Comment by jessicabarnett8219** [comment]
What does it mean to include representation? Is that nested data?

**Comment by Kazathur92** [comment]
want a completed column in model? or completed already searches for date that isnt today?

**Comment by CosignMyCodesign** [comment]
Bullet point 2: That is built into the model based on how we set up that relationship, correct?
